import "./globals.css"
import { Providers } from "./redux/provider"
// import Footer from "./component/footer/footer"
import dynamic from "next/dynamic"


const Navbar = dynamic(()=> import('./component/navbar/navbar'))



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

  }


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <header>
            <Navbar />
          </header>
          <main>{children}</main>
          {/* <footer>
            <Footer />
          </footer> */}
        </Providers>
      </body>
    </html>
  )
}
