import "./globals.css"
<<<<<<< HEAD
import { Providers } from "./redux/provider"
// import Footer from "./component/footer/footer"
import dynamic from "next/dynamic"


const Navbar = dynamic(()=> import('./component/navbar/navbar'))

=======
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Providers } from "./redux/provider"
import dynamic from "next/dynamic"

const Navbar = dynamic(()=>import('./component/navbar/page'))
const Footer = dynamic(()=>import("./component/footer/page"))
>>>>>>> branch


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

  }


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <header>
            <Navbar />
          </header>
          <main>{children}</main>
<<<<<<< HEAD
          {/* <footer>
            <Footer />
          </footer> */}
=======
          <footer>
            <Footer/>
          </footer>
>>>>>>> branch
        </Providers>
      </body>
    </html>
  )
}
